<?php
/**
 * @file
 * Code for the redhen_demo feature.
 */

include_once 'redhen_demo.features.inc';

/**
 * Implements hook_user_view().
 */
function redhen_demo_user_view($account, $view_mode, $langcode) {
  $contact = redhen_contact_load_by_user($account);
  if ($contact) {
    if ($contact->engagement_score > 100) {
      drupal_set_message('Thank you for supporting our organization!');
    }
  }
}

/**
 * Implements hook_entity_view().
 */
function redhen_demo_entity_view($entity, $type, $view_mode, $langcode) {
  if ($type == 'node' && $entity->type == 'blog' && $view_mode == 'full') {
    global $user;
    $contact = redhen_contact_load_by_user($user);
    if ($contact) {
      list($id, $vid, $bundle) = entity_extract_ids($type, $entity);
      $engagement = redhen_engagement_create('comment', $contact->contact_id, 'Viewed a blog post', $type, $id);
      $engagement->save();
    }
  }
}
